### ISSUE TITLE
Feature request: Option to generate index locally

### ISSUE THREAD

**Issue by aerohub** [LouisBarranqueiro/hexo-algoliasearch#22]
Hello there!

Sometimes I work with a very slow internet connection and in this case not all the posts of my site are indexed on Algolia. I get this error:

```
...
INFO  716 posts collected
INFO  Clearing index on Algolia...
INFO  Index cleared
INFO  Indexing posts on Algolia...
INFO  Error has occurred during indexing posts : AlgoliaSearchNetworkError: connect ETIMEDOUT 195.189.123.143:443

F:\site\node_modules\hexo-algoliasearch\lib\algolia.js:105
        throw err;
        ^
AlgoliaSearchNetworkError: connect ETIMEDOUT 195.189.123.143:443
    at ClientRequest.error (F:\site\node_modules\algoliasearch\src\server\builds\node.js:213:14)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

But index can be downloaded to Algolia as a file using their dashboard. Is it possible to have some option (some `hexo algolia -l` or `--local`) to generate index file locally?

> Supported formats (max. 50 MB):
> JSON: containing either a single object or an array of objects
> CSV: comma separated, first line as header
> TSV: tab separated, first line as header

Or, may be, any improvements are possible for indexing time?

Thank you!

**Comment by LouisBarranqueiro** [comment]
👋 @aerohub, No, sorry, I do not plan to add any new features or improvements for this module.
